-- Baseline schema - khớp chính xác với cấu trúc bảng mà Hibernate
-- (spring.jpa.hibernate.ddl-auto=update) đã tự sinh ra trước khi chuyển sang
-- Flyway. Từ migration này trở đi, Flyway là nguồn sự thật duy nhất cho schema
-- (spring.jpa.hibernate.ddl-auto=validate - Hibernate chỉ kiểm tra khớp, không
-- tự sửa DDL nữa).
CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    code VARCHAR(30) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE,
    full_name VARCHAR(100),
    role VARCHAR(20) NOT NULL,
    created_at TIMESTAMP,
    department_id BIGINT REFERENCES departments (id),
    CONSTRAINT users_role_check CHECK (role IN ('ADMIN', 'DEPT_ADMIN', 'DATA_OWNER', 'DATA_USER'))
);

CREATE TABLE attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_name VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(255),
    created_at TIMESTAMP,
    issuer_department_id BIGINT REFERENCES departments (id)
);

CREATE TABLE user_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id),
    attribute_id BIGINT NOT NULL REFERENCES attributes (id),
    assigned_at TIMESTAMP,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    issued_by_user_id BIGINT REFERENCES users (id),
    CONSTRAINT uk_user_attributes_user_attribute UNIQUE (user_id, attribute_id)
);

CREATE TABLE file_metadata (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    access_policy TEXT NOT NULL,
    encrypted_aes_key TEXT NOT NULL,
    owner_id BIGINT NOT NULL REFERENCES users (id),
    file_size BIGINT,
    content_type VARCHAR(100),
    created_at TIMESTAMP
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(30) NOT NULL,
    file_id BIGINT NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    owner_id BIGINT NOT NULL,
    owner_username VARCHAR(50) NOT NULL,
    requester_id BIGINT NOT NULL,
    requester_username VARCHAR(50) NOT NULL,
    access_policy TEXT,
    detail TEXT,
    occurred_at TIMESTAMP
);
